name: Generate Snake Animation

on:

  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: Platane/snk@v2
        with:
          github_user_name: irushub
          output: dist/snake.svg

      - name: Commit and push the result
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/snake.svg
          git commit -m "Generate snake animation"
          git push
