name: Generate Snake Animation and Deploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: Platane/snk@v2
        with:
          github_user_name: irushub
          output: dist/snake.svg

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add dist/snake.svg
          git commit -m "Deploy to GitHub Pages"
          git push --force "https://${{ secrets.GH_PAT }}@github.com/irushub/irushub.git" HEAD:gh-pages
